/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.13.0.56.2 */
/* Module Version: 5.7 */
/* Mon Nov 03 13:12:30 2025 */

/* parameterized module instance */
PLL __ (.CLKI( ), .RST( ), .CLKOP( ), .CLKOS( ), .LOCK( ));
